<a href="https://colab.research.google.com/github/Asfia-Fathima/Statistical-Analytics-computing/blob/main/lab_2_(24_02_2025).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This includes-

~Array Creation & Properties.

~Array Indexing & Slicing.

~Reshaping & Flattening.

~Mathematical Operations(elementwise,statistical& aggregation).

~Stacking & Concatenation.

~Universal Functions (ufuncs)(Arithmetic,trigonometric,logarithmic,exponential,Rounding).



In [ ]:
#12# Write a python script to perform following operations on arrays
##WORKING WITH ARRAYS(“2”)
##1D ARRAY OPERATIONS
import numpy as np
arr1D=np.array([1,2,3,4,5])      #(a)create 1d array
boolArray = np.array([True, False, True, False,True])
print("boolean array=",boolArray);   #(b)create a boolean array
print("1D Array operations")
print("original 1D array=",arr1D)
print("Shape=",arr1D.shape)
print("Size=",arr1D.size)
print("datatype=",arr1D.dtype)
print("Sum=",np.sum(arr1D))
print("mean=",np.mean(arr1D))
print("median=",np.median(arr1D))
print("Min=",np.min(arr1D))
print("Max=",np.max(arr1D))
print("Standard deviation=",np.std(arr1D))
print("Reshaped=",arr1D.reshape(5,1)) #(f.) Reshape an array
print("Reversed=",arr1D[::-1])
print("Transpose=",arr1D.T)
print("Reversed=",arr1D[::-1])
print("Square=",np.square(arr1D))

boolean array= [ True False  True False  True]
1D Array operations
original 1D array= [1 2 3 4 5]
Shape= (5,)
Size= 5
datatype= int64
Sum= 15
mean= 3.0
median= 3.0
Min= 1
Max= 5
Standard deviation= 1.4142135623730951
Reshaped= [[1]
 [2]
 [3]
 [4]
 [5]]
Reversed= [5 4 3 2 1]
Transpose= [1 2 3 4 5]
Reversed= [5 4 3 2 1]
Square= [ 1  4  9 16 25]


In [ ]:
  #(c) Extract items that satisfy a given condition from 1D array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = array[array % 2 == 0]
print("Extracted values=",even_numbers)


Extracted values= [ 2  4  6  8 10]


In [ ]:
#(d)Replace items that satisfy a condition with another value in numpy array
replace=np.array([1, 2, 3, 4, 55, 6, 7, 18, 9, 12])# Replace even numbers with 0
replace[replace % 2 == 0] = 0
print("replaced values=",replace)


replaced values= [ 1  0  3  0 55  0  7  0  9  0]


In [ ]:
#(e). Replace items that satisfy a condition without affecting the original array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
new_array = np.where(array % 2 == 0, 0, array)
print("replaced without affecting the values=",new_array)


replaced without affecting the values= [1 0 3 0 5 0 7 0 9 0]


In [ ]:
#(g)Extract all numbers between a given range from a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
start = 3
end = 7
result = array[(array >= start) & (array <= end)]
print("all numbers between a given range are",result)

all numbers between a given range are [3 4 5 6 7]


In [ ]:
#3 Multiple array
## 2D ARRAY OPERATIONS##
import numpy as np
arr1=np.array([[1,2,3],[2,3,4],[2,3,1]])
arr2=np.array([[1,2,3],[1,2,3],[1,2,3]])
print("2D Array operations")
print("array1 elements",arr1)
print("array2 elements=",arr2)
print("array1 Shape=",arr1.shape)
print("array1 Size=",arr1.size)
print("array2 Shape=",arr1.shape)
print("array2 Size=",arr1.size)
print("Array1 datatype=",arr1.dtype)
print("Array2 datatype=",arr2.dtype)
print("Sum using plus operation=\n",arr1+arr2)
print("Sum using add function=\n",np.add(arr1,arr2))
print("Mean=",np.mean(arr1))
print("Min=",np.min(arr1))
print("Max=",np.max(arr1))
print("ARR1 Standard deviation=",np.std(arr1))
print("ARR2 Standard deviation=",np.std(arr2))
print("Array1 Reshaped=",arr1.reshape(9,1))
print("Array2 Reshaped=",arr2.reshape(9,1))
print("Array1 Reversed=",arr1[::-1])
print("Array2 Reversed=",arr2[::-1])
print("Transpose=",arr1.T)
print("Square=",np.square(arr2))
print("Flatten=",arr1.flatten())


2D Array operations
array1 elements [[1 2 3]
 [2 3 4]
 [2 3 1]]
array2 elements= [[1 2 3]
 [1 2 3]
 [1 2 3]]
array1 Shape= (3, 3)
array1 Size= 9
array2 Shape= (3, 3)
array2 Size= 9
Array1 datatype= int64
Array2 datatype= int64
Sum using plus operation=
 [[2 4 6]
 [3 5 7]
 [3 5 4]]
Sum using add function=
 [[2 4 6]
 [3 5 7]
 [3 5 4]]
Mean= 2.3333333333333335
Min= 1
Max= 4
ARR1 Standard deviation= 0.9428090415820634
ARR2 Standard deviation= 0.816496580927726
Array1 Reshaped= [[1]
 [2]
 [3]
 [2]
 [3]
 [4]
 [2]
 [3]
 [1]]
Array2 Reshaped= [[1]
 [2]
 [3]
 [1]
 [2]
 [3]
 [1]
 [2]
 [3]]
Array1 Reversed= [[2 3 1]
 [2 3 4]
 [1 2 3]]
Array2 Reversed= [[1 2 3]
 [1 2 3]
 [1 2 3]]
Transpose= [[1 2 2]
 [2 3 3]
 [3 4 1]]
Square= [[1 4 9]
 [1 4 9]
 [1 4 9]]
Flatten= [1 2 3 2 3 4 2 3 1]


In [ ]:
#PROGRAM3# INDEX SLICING OPERATIONS
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:1])
print(arr[:4])
print(arr[-3:-1])
print(arr[::2])


[2 3 4 5]
[]
[1 2 3 4]
[5 6]
[1 3 5 7]


In [ ]:
 #3#STACKING OPERATIONS
#a. Stack two arrays vertically b. Stack two arrays horizontally
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print("VERTICALLY STACKED=",np.vstack((arr1,arr2)))
print("HORIZONTALLY STACKED=",np.hstack((arr1,arr2)))


VERTICALLY STACKED= [[1 2]
 [3 4]
 [5 6]
 [7 8]]
HORIZONTALLY STACKED= [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
 ##Statistical operations
arr1=np.array([[1,2,3],[2,3,4],[2,3,1]])
arr2=np.array([[1,2,3],[1,2,3],[1,2,3]])
print("Mean=",np.mean(arr1))
print("Min=",np.min(arr1))
print("Max=",np.max(arr1))
print("ARR1 Standard deviation=",np.std(arr1))
print("ARR2 Standard deviation=",np.std(arr2))


Mean= 2.3333333333333335
Min= 1
Max= 4
ARR1 Standard deviation= 0.9428090415820634
ARR2 Standard deviation= 0.816496580927726


In [ ]:
 ##Arithmetic functions
arr1D=np.array([1,2,3,4,5])
arr2D=np.array([6,7,8,9,0])
print("Addition=",np.add(arr1,arr2))
print("Subtraction=",np.subtract(arr1,arr2))
print("Multiplication=",np.multiply(arr1,arr2))


Addition= [[2 4 6]
 [3 5 7]
 [3 5 4]]
Subtraction= [[ 0  0  0]
 [ 1  1  1]
 [ 1  1 -2]]
Multiplication= [[ 1  4  9]
 [ 2  6 12]
 [ 2  6  3]]


In [ ]:
 ##Trigonometric functions

import numpy as np
# Define angles in degrees
angle_degrees = np.array([30, 20, 5])
 # Convert to radians
angle_radians = np.radians(angle_degrees)
 # Compute trigonometric functions
print("Sine =", np.sin(angle_radians))
print("Cosine =", np.cos(angle_radians))
print("Tangent =", np.tan(angle_radians))


Sine = [0.5        0.34202014 0.08715574]
Cosine = [0.8660254  0.93969262 0.9961947 ]
Tangent = [0.57735027 0.36397023 0.08748866]
