<a href="https://colab.research.google.com/github/Asfia-Fathima/Statistical-Analytics-computing/blob/main/lab_4_(10_03_2025).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This contains-

~Perform the following Boolean functions(any,all,where)

~Perform the following sorting methods (argsort,unique)



In [1]:
##boolean functions
import numpy as np
##”ALL”
newarr=[1,2,3]
boolarr=[True,False,True]
resnewarr=np.all(newarr)
print(resnewarr)
resboolarr=np.all(boolarr)
print(boolarr)

##”ANY”
import numpy as np
newarr=[1,2,3]
boolarr=[True,False,True]
resnewarr=np.any(newarr)
print(resnewarr)
resboolarr=np.any(boolarr)
print(resboolarr)

#”WHERE”
import numpy as np
arr=np.array([4,5,6,7,8])
result=np.where(arr>5,'high','low')
print(result)


True
[True, False, True]
True
True
['low' 'low' 'high' 'high' 'high']


In [2]:
##sorting methods
a=[6,5,4,3,2,1]
print(np.sort(a))

import numpy as np
a=[5,4,3,2,1]
print(np.argsort(a))


import numpy as np
a=[5,4,3,2,1,2,4,3,5,6,9]
print(np.unique(a))


[1 2 3 4 5 6]
[4 3 2 1 0]
[1 2 3 4 5 6 9]
