<a href="https://colab.research.google.com/github/Asfia-Fathima/Statistical-Analytics-computing/blob/main/Lab_3_(03_03_2025).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This contains -

~Linear Algebra Functions.

~Broadcasting

~File Reading & Writing(text(load,save),binary(load,save))

In [1]:
##linear algebra functions
import numpy as np
a=np.array([[1,2,3],[5,2,3],[1,9,3]])
b=np.array([[1,2,3],[1,2,3],[1,2,3]])
print("Transpose=\n",a.T)
print("Determinant of matrix\n",np.linalg.det(a))
print("Inverse of a matrix\n",np.linalg.inv(a))
print("Inverse of a matrix\n",np.linalg.inv(a))
print("Rank of a matrix\n",np.linalg.matrix_rank(a))
print("matrix multiplication:\n",np.dot(a,b))
print("\nComputes eigenvalues and eigenvectors\n\n",np.linalg.eig(a))
print("\nSingular Value Decomposition\n\n",np.linalg.svd(a))


Transpose=
 [[1 5 1]
 [2 2 9]
 [3 3 3]]
Determinant of matrix
 83.99999999999999
Inverse of a matrix
 [[-2.50000000e-01  2.50000000e-01  0.00000000e+00]
 [-1.42857143e-01  3.22739251e-18  1.42857143e-01]
 [ 5.11904762e-01 -8.33333333e-02 -9.52380952e-02]]
Inverse of a matrix
 [[-2.50000000e-01  2.50000000e-01  0.00000000e+00]
 [-1.42857143e-01  3.22739251e-18  1.42857143e-01]
 [ 5.11904762e-01 -8.33333333e-02 -9.52380952e-02]]
Rank of a matrix
 3
matrix multiplication:
 [[ 6 12 18]
 [10 20 30]
 [13 26 39]]

Computes eigenvalues and eigenvectors

 EigResult(eigenvalues=array([ 9.8228643 +0.j        , -1.91143215+2.21312095j,
       -1.91143215-2.21312095j]), eigenvectors=array([[ 0.37819396+0.j        , -0.25822663-0.35415448j,
        -0.25822663+0.35415448j],
       [ 0.53219953+0.j        , -0.39397114+0.22980499j,
        -0.39397114-0.22980499j],
       [ 0.75745164+0.j        ,  0.77451276+0.j        ,
         0.77451276-0.j        ]]))

Singular Value Decomposition

 SVDResult(U

In [2]:
## Broadcasting
import numpy as np
arr1=np.array([[1,2,3],[2,3,4],[2,3,1]])
arr2=np.array([[1,2,3],[1,2,3],[1,2,3]])
print("broadcasting arr and scalar\n",arr1+5)
print("Adding 1d arr t0 2d array\n",arr1+arr2)


broadcasting arr and scalar
 [[6 7 8]
 [7 8 9]
 [7 8 6]]
Adding 1d arr t0 2d array
 [[2 4 6]
 [3 5 7]
 [3 5 4]]


In [4]:
#File Reading & Writing(text(load,save),binary(load,save))
##FILE HANDLING##
import numpy as np
# Saving an array to a text file
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt("D:\\output.txt", arr, delimiter=",")
print("Array saved to array.txt")
# Loading data from a text file
filename = "D:\\output.txt"
data = np.loadtxt(filename, delimiter=",")
print(data)


Array saved to array.txt
[[1. 2. 3.]
 [4. 5. 6.]]
